project: 'TextMining_MC'
version: '0.1.0'
project_path:
paths:
    project: ''
    data:
        root: 'data'
        pubmed : 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/'

resources:
    pubtator: ''
